### PR TITLE
Updated UI

### PR DESCRIPTION
**Pull request by eroshin**

### CODE REVIEW

**Comment by amulware** [comment]
Looking pretty good overall!

A few comments:

- When swiping from one screen to the other, if the user swipes slowly they can see that the timers stand still for that time, and then quickly hurry back to the correct time after the swipe. Would it be possible for the animations to continue running and the timers to update during the swipe?
- When the timer is reset at 00:00:00, there also is a 0-time entry in the history list. This should not be shown. The entry should only appear once the timer starts.
- Navigation to the log screen should only be possible when there is at least one proper entry in the list (and the icon in the top right corner should only be shown then too).
- The swiping hint appears to pop into existence. It should instead do a quick fading animation.

BUGS:
- Not sure exactly how to reproduce this, but I was able to get two mini-clock-faces in the log, with one animating properly, and the other just sitting there.
- Also, the darker faced time in the log shows "0 sec" for running timers, instead of the correct time.
screen shot 2016-08-11 at 14 11 41


@pe0ny In the current implementation, shaking the phone while on the log-screen, with the timer stopped, resets the timer. Is this alright, or should resetting only work on the main timer screen?

**Comment by pe0ny** [comment]
@amulware Shaking should be available on the log screen as well. Eg when timer is running and user is on the log screen, and shakes the phone then TE should be stopped/reset.

**Comment by amulware** [comment]
Please clarify: shaking should reset the timer, even fi the timer is running? That is different than the current implementation. Currently, the timer can only be reset while stopped (and this works on either screen).

**Comment by pe0ny** [comment]
Yes. Sorry, my bad. Wrong term 😇  Only paused TE can be stopped and that should work on both screens (timer screen and log screen).

**Comment by amulware** [comment]
Then that is how it should be. Very good.

**Pull request closed without merging**
